### ISSUE TITLE
[feat] 메인 화면

### ISSUE THREAD

**Issue by sebbbin** [hapjuhasil/Back-end#28]
## 🛠 Issue

메인 화면에 들어갈 기능들 

## 📝 To-do

- [x] 1) 현재 로컬 시간보다 이후에 있는 예약들 get -> 멤버별 예약 리스트 get해오는 거로 한번에 퉁 가능
- [x] 2) 원래 기능 ) 추천 합주실 -> 그냥 전체 합주실에서 3개 get
- [ ] 3) 사용자가 이용했던 곳 3개 get
